; This file was auto-generated by drush make
core = 7.x
api = 2

; Modules
projects[baidu_analytics][subdir] = "contrib"
projects[baidu_analytics][version] = "1.0"

projects[better_formats][subdir] = "contrib"
projects[better_formats][version] = "1.0-beta1+2-dev"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.4"

projects[clientside_validation][subdir] = "contrib"
projects[clientside_validation][version] = "1.41"

projects[date][subdir] = "contrib"
projects[date][version] = "2.8"

projects[ds][subdir] = "contrib"
projects[ds][version] = "2.7"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.5"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.1"

projects[field_placeholder][subdir] = "contrib"
projects[field_placeholder][version] = "1.0"

projects[field_validation][subdir] = "contrib"
projects[field_validation][version] = "2.4"

projects[flag][subdir] = "contrib"
projects[flag][version] = "3.5"

projects[fpa][subdir] = "contrib"
projects[fpa][version] = "2.6"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.4"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.4"

projects[l10n_update][subdir] = "contrib"
projects[l10n_update][version] = "1.0"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[link][subdir] = "contrib"
projects[link][version] = "1.3"

projects[metatag][subdir] = "contrib"
projects[metatag][version] = "1.4"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "2.0-alpha2"

projects[navbar][subdir] = "contrib"
projects[navbar][version] = "1.4"

projects[nodequeue][subdir] = "contrib"
projects[nodequeue][version] = "2.0-beta1"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[r4032login][subdir] = "contrib"
projects[r4032login][version] = "1.8"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[ueditor][subdir] = "contrib"
projects[ueditor][version] = "2.4"

projects[uuid][subdir] = "contrib"
projects[uuid][version] = "1.0-alpha6"

projects[views][subdir] = "contrib"
projects[views][version] = "3.8"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = ""
libraries[backbone][download][url] = ""
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ueditor][download][type] = ""
libraries[ueditor][download][url] = ""
libraries[ueditor][directory_name] = "ueditor"
libraries[ueditor][type] = "library"